// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi p2p REST API specification
A draft to p2p rest API specification


    Schemes:
      http
    Host: localhost
    BasePath: /
    Version: 0.1.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
