// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi API specification for Gorjun
Gorjun is a golang replacement for Kurjun project. Kurjun is Subutai's CDN software.


    Schemes:
      http
      https
    Host: localhost
    BasePath: /
    Version: 0.1.0

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
