// Code generated by go-swagger; DO NOT EDIT.

package restapi

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
)

// SwaggerJSON embedded version of the swagger document used at generation time
var SwaggerJSON json.RawMessage

func init() {
	SwaggerJSON = json.RawMessage([]byte(`{
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "schemes": [
    "http",
    "https"
  ],
  "swagger": "2.0",
  "info": {
    "description": "Gorjun is a golang replacement for Kurjun project. Kurjun is Subutai's CDN software.",
    "title": "API specification for Gorjun",
    "version": "0.1.0"
  },
  "paths": {
    "/kurjun/rest/apt/list": {
      "get": {
        "description": "Info returns JSON formatted list of elements. It allows to apply some filters to Search.",
        "tags": [
          "gorjun",
          "apt",
          "list"
        ],
        "operationId": "aptList",
        "parameters": [
          {
            "type": "integer",
            "format": "int32",
            "name": "id",
            "in": "query"
          },
          {
            "type": "string",
            "name": "tag",
            "in": "query"
          },
          {
            "type": "string",
            "name": "name",
            "in": "query"
          },
          {
            "type": "string",
            "name": "owner",
            "in": "query"
          },
          {
            "type": "string",
            "name": "token",
            "in": "query"
          },
          {
            "type": "string",
            "name": "subname",
            "in": "query"
          },
          {
            "type": "string",
            "name": "version",
            "in": "query"
          },
          {
            "type": "boolean",
            "name": "verified",
            "in": "query"
          }
        ],
        "responses": {
          "200": {
            "description": "turns JSON formatted list of elements",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/listItem"
              }
            }
          },
          "default": {
            "description": "generic error response",
            "schema": {
              "x-swagger-router-controller": "Default"
            }
          }
        }
      }
    }
  },
  "definitions": {
    "error": {
      "type": "object",
      "required": [
        "message"
      ],
      "properties": {
        "code": {
          "type": "integer",
          "format": "int64"
        },
        "message": {
          "type": "string"
        }
      }
    },
    "listItem": {
      "type": "object",
      "required": [
        "name"
      ],
      "properties": {
        "archteture": {
          "type": "string",
          "minLength": 1
        },
        "date": {
          "type": "array",
          "minLength": 1,
          "items": {
            "type": "string"
          }
        },
        "description": {
          "type": "string",
          "minLength": 1
        },
        "filename": {
          "type": "string",
          "minLength": 1
        },
        "hash": {
          "type": "string",
          "minLength": 1
        },
        "id": {
          "type": "string",
          "readOnly": true
        },
        "name": {
          "type": "string",
          "minLength": 1
        },
        "owner": {
          "type": "string",
          "minLength": 1
        },
        "parent": {
          "type": "string",
          "minLength": 1
        },
        "prefsize": {
          "type": "string",
          "minLength": 1
        },
        "signature": {
          "type": "string",
          "minLength": 1
        },
        "size": {
          "type": "array",
          "minLength": 1,
          "items": {
            "type": "string"
          }
        },
        "tags": {
          "type": "string",
          "minLength": 1
        },
        "timestamp": {
          "type": "string",
          "minLength": 1
        },
        "version": {
          "type": "string",
          "minLength": 1
        }
      }
    }
  }
}`))
}
