swagger: "2.0"
consumes:
- application/json
info:
  description: Gorjun is a golang replacement for Kurjun project. Kurjun is Subutai's
    CDN software.
  title: API specification for Gorjun
  version: 0.1.0
produces:
- application/json
schemes:
- http
- https
paths:
  /kurjun/rest/apt/list:
    get:
      tags: 
        - gorjun 
        - apt
        - list
      operationId: aptList
      description: Info returns JSON formatted list of elements. It allows to apply some filters to Search.
      parameters: 
        - name: id
          in: query
          type: integer
          format: int32
        - name: tag
          in: query
          type: string
        - name: name
          in: query
          type: string
        - name: owner
          in: query
          type: string
        - name: token
          in: query
          type: string
        - name: subname
          in: query
          type: string
        - name: version
          in: query
          type: string
        - name: verified
          in: query
          type: boolean
      responses:
        '200':
          description: turns JSON formatted list of elements
          schema:
            type: array
            items:
              $ref: "#/definitions/listItem"
        default:
          description: generic error response
          schema:
            x-swagger-router-controller: Default
definitions:
  listItem:
    type: object
    required:
      - name
    properties:
      id:
        type: string
        readOnly: true
      hash:
        type: string
        minLength: 1
      size:
        type: array
        items:
          type: string
        minLength: 1
      date:
        type: array
        items:
          type: string
        minLength: 1
      timestamp:
        type: string
        minLength: 1
      name:
        type: string
        minLength: 1
      tags:
        type: string
        minLength: 1
      owner:
        type: string
        minLength: 1
      parent:
        type: string
        minLength: 1
      version:
        type: string
        minLength: 1
      filename:
        type: string
        minLength: 1
      prefsize:
        type: string
        minLength: 1
      signature:
        type: string
        minLength: 1
      description:
        type: string
        minLength: 1
      archteture:
        type: string
        minLength: 1
  error:
    type: object
    required:
      - message
    properties:
      code:
        type: integer
        format: int64
      message:
        type: string